branch-defaults:
  master:
    environment: null
    group_suffix: null

global:
  application_name: nodejs_aws_bff_aleksbychyk
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: eu-west-1 
  include_git_submodules: true
  instance_profile: null 
  platform_name: null 
  platform_version: null 
  profile: private
  sc: git 
  workspace_type: Application