service: authentication-service

app: aleks-rs-app-app
org: aleksbyczyk

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: eu-west-1
  profile: private
  stage: dev
  httpApi:
    cors: true
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    AliakseiBychyk: ${ssm:/auth-password~true}

functions:

  BasicAuthorizer:
    handler: handler.basicAuthorizer

resources:
  Outputs:
    BasicAuthorizerQualifiedArn:
      Description: Basic Token Authorizer
      Export:
        Name: BasicAuthorizerArn