service: authentication-service

app: aleks-rs-app-app
org: aleksbyczyk

frameworkVersion: '2'
variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: eu-west-1
  profile: private
  stage: dev
  httpApi:
    cors: true
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    AliakseiBychyk: ${ssm:/auth-password}

functions:
  BasicAuthorizer:
    handler: handler.basicAuthorizer
    description: Basic Token Authorizer

resources:
  Outputs:
    BasicAuthorizerLambdaFunctionQualifiedArn:
      Description: Basic Token Authorizer Arn
      Export:
        Name: BasicAuthorizerArn