service: cart-service

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  profile: private

functions:
  cart: 
    handler: handler.cart
    events:
      - http:
          path: cart
          method: get 
          cors: true 
