service: import-service

app: aleks-rs-app-app
org: aleksbyczyk

frameworkVersion: '2'
variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: eu-west-1
  profile: private
  stage: dev
  httpApi:
    cors: true
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    BUCKET_NAME: !Ref ProductsS3Bucket
    SQS_URL: !ImportValue ProductsSqsQueue
  iam: 
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:ListBucket
          Resource: 
            - !GetAtt ProductsS3Bucket.Arn
        - Effect: Allow
          Action:
            - s3:*
          Resource: 
            - !Sub ${ProductsS3Bucket.Arn}/*
        - Effect: Allow
          Action:
            - sqs:*
          Resource:
            - !ImportValue ProductsSqsQueueArn

plugins:
  - serverless-webpack
  
custom:
  s3BucketName: aleksbyczyk-import-service-bucket
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  
functions:
  importProductFile: 
    handler: handler.importProductsFile
    description: Provides signed url for upload a .csv file
    events:
      - http:
          method: GET
          path: /import
          cors: true
          # authorizer:
          #   name: basicTokenRequestAuthorizer
          #   type: token
          #   identitySource: method.request.header.Authorization
          #   resultTtlInSeconds: 0
          #   arn: !ImportValue BasicAuthorizerArn
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: !ImportValue CognitoAuthorizer

  importFileParser:
    handler: handler.importFileParser
    description: Parses .csv file and move processed .csv into /parsed folder
    events:
      - s3:
          bucket: !Ref ProductsS3Bucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
            - suffix: .csv
          existing: true

resources:
  Resources:
    ## S3 Bucket
    ProductsS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.s3BucketName}
        AccessControl: PublicRead
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
              AllowedOrigins:
                - '*'
    
    ## S3 Bucket Policy  
    ProductsS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref ProductsS3Bucket
        PolicyDocument:
          Statement:
            - Sid: AllowPublicRead
              Effect: Allow
              Action: s3:GetObject
              Resource: !Sub ${ProductsS3Bucket.Arn}/*
              Principal:
                AWS: '*'

 
    ## Gateway Response
    GatewayResponseDefault4xx:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
        ResponseType: DEFAULT_4XX
        RestApiId: !Ref ApiGatewayRestApi

  Outputs:
    ProductsS3BucketOutput:
      Description: S3 bucket for products
      Value: !Ref ProductsS3Bucket     
